name: Deploy Richnote Server to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy-backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "22.11.0"

      - name: Install Dependencies
        run: npm install
        working-directory: .

      - name: Deploy Server Files to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "./*"
          target: "/home/ubuntu/richnote/richnote-server"

      - name: Restart Server with PM2
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/ubuntu/richnote/richnote-server
            npm install
            pm2 delete richnote-server || true
            npm start
            pm2 save
